//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiBandImport.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiBandImport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expiration time ähnelt.
        /// </summary>
        internal static string Ablaufzeit {
            get {
                return ResourceManager.GetString("Ablaufzeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action required ähnelt.
        /// </summary>
        internal static string AktionErforderlich {
            get {
                return ResourceManager.GetString("AktionErforderlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wake-up time ähnelt.
        /// </summary>
        internal static string Aufwachzeit {
            get {
                return ResourceManager.GetString("Aufwachzeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm backup on your Smartphone ähnelt.
        /// </summary>
        internal static string BackupBestätigen {
            get {
                return ResourceManager.GetString("BackupBestätigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission ähnelt.
        /// </summary>
        internal static string Berechtigung {
            get {
                return ResourceManager.GetString("Berechtigung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string Beschreibung {
            get {
                return ResourceManager.GetString("Beschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date / time ähnelt.
        /// </summary>
        internal static string DatumUhrzeit {
            get {
                return ResourceManager.GetString("DatumUhrzeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sleep time ähnelt.
        /// </summary>
        internal static string Einschlafzeit {
            get {
                return ResourceManager.GetString("Einschlafzeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End ähnelt.
        /// </summary>
        internal static string Ende {
            get {
                return ResourceManager.GetString("Ende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance ähnelt.
        /// </summary>
        internal static string Entfernung {
            get {
                return ResourceManager.GetString("Entfernung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result of the action ähnelt.
        /// </summary>
        internal static string ErgebnisAktion {
            get {
                return ResourceManager.GetString("ErgebnisAktion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following error appeared ähnelt.
        /// </summary>
        internal static string FehlerMsg {
            get {
                return ResourceManager.GetString("FehlerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not connect to phone. ähnelt.
        /// </summary>
        internal static string FehlerPhoneNotAvabile {
            get {
                return ResourceManager.GetString("FehlerPhoneNotAvabile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workdirk on phone not found. Last read data will be viewed. ähnelt.
        /// </summary>
        internal static string FehlerWorkDirPhone {
            get {
                return ResourceManager.GetString("FehlerWorkDirPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Walk Distance ähnelt.
        /// </summary>
        internal static string GehenEntfernung {
            get {
                return ResourceManager.GetString("GehenEntfernung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Walk Calories ähnelt.
        /// </summary>
        internal static string GehenKalorien {
            get {
                return ResourceManager.GetString("GehenKalorien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Walk time ähnelt.
        /// </summary>
        internal static string GehenZeit {
            get {
                return ResourceManager.GetString("GehenZeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID ähnelt.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index ähnelt.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Json String ähnelt.
        /// </summary>
        internal static string JsonString {
            get {
                return ResourceManager.GetString("JsonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calories ähnelt.
        /// </summary>
        internal static string Kalorien {
            get {
                return ResourceManager.GetString("Kalorien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run distance ähnelt.
        /// </summary>
        internal static string LaufenEntfernung {
            get {
                return ResourceManager.GetString("LaufenEntfernung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Running calories ähnelt.
        /// </summary>
        internal static string LaufenKalorien {
            get {
                return ResourceManager.GetString("LaufenKalorien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run-time ähnelt.
        /// </summary>
        internal static string Laufzeit {
            get {
                return ResourceManager.GetString("Laufzeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die light sleeping ähnelt.
        /// </summary>
        internal static string LeichtenSchlaf {
            get {
                return ResourceManager.GetString("LeichtenSchlaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LUA Script ähnelt.
        /// </summary>
        internal static string LuaScript {
            get {
                return ResourceManager.GetString("LuaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minutes ähnelt.
        /// </summary>
        internal static string Minuten {
            get {
                return ResourceManager.GetString("Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Raw activity ähnelt.
        /// </summary>
        internal static string RohdatenAktivität {
            get {
                return ResourceManager.GetString("RohdatenAktivität", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Raw Sensordata ähnelt.
        /// </summary>
        internal static string RohdatenSensorwert {
            get {
                return ResourceManager.GetString("RohdatenSensorwert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sleep duration ähnelt.
        /// </summary>
        internal static string Schlafdauer {
            get {
                return ResourceManager.GetString("Schlafdauer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steps ähnelt.
        /// </summary>
        internal static string Schritte {
            get {
                return ResourceManager.GetString("Schritte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Script Version ähnelt.
        /// </summary>
        internal static string ScriptVersion {
            get {
                return ResourceManager.GetString("ScriptVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activity ähnelt.
        /// </summary>
        internal static string Taetigkeit {
            get {
                return ResourceManager.GetString("Taetigkeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deep sleep ähnelt.
        /// </summary>
        internal static string Tiefschlaf {
            get {
                return ResourceManager.GetString("Tiefschlaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        internal static string Typ {
            get {
                return ResourceManager.GetString("Typ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wake ähnelt.
        /// </summary>
        internal static string Wach {
            get {
                return ResourceManager.GetString("Wach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Goal steps ähnelt.
        /// </summary>
        internal static string ZielSchritte {
            get {
                return ResourceManager.GetString("ZielSchritte", resourceCulture);
            }
        }
    }
}
